import {
  AlertCircle,
  Brain,
  BookOpen,
  Camera,
  Check,
  CheckCircle2,
  Circle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardCheck,
  ClipboardList,
  Copy,
  Download,
  ExternalLink,
  Eye,
  FileText,
  Home,
  House,
  HouseAlert,
  LoaderCircle,
  MapPin,
  Images,
  Layers3,
  Lightbulb,
  ListChecks,
  Newspaper,
  Phone,
  Pencil,
  Pill,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Send,
  Save,
  Shield,
  Star,
  Trash2,
  Trophy,
  User,
  UserRoundCheck,
  UserRoundX,
  Waves,
  WifiOff,
  X,
} from "lucide-react-native";
import { Icon } from "./ui/icon";

export const APP_ICONS = {
  account: User,
  "account-alert": UserRoundX,
  "account-check": UserRoundCheck,
  "alert-circle": AlertCircle,
  autorenew: RefreshCw,
  brain: Brain,
  "book-open": BookOpen,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-outline": Circle,
  "clipboard-list": ClipboardList,
  "clipboard-pulse": ClipboardCheck,
  close: X,
  "content-copy": Copy,
  "content-save": Save,
  camera: Camera,
  download: Download,
  "external-link": ExternalLink,
  eye: Eye,
  "file-document": FileText,
  home: Home,
  "home-alert": HouseAlert,
  loading: LoaderCircle,
  "map-marker-radius": MapPin,
  images: Images,
  layers: Layers3,
  lightbulb: Lightbulb,
  "list-checks": ListChecks,
  "medical-bag": Pill,
  newspaper: Newspaper,
  pencil: Pencil,
  phone: Phone,
  play: Play,
  plus: Plus,
  replay: RotateCcw,
  send: Send,
  save: Save,
  shield: Shield,
  star: Star,
  "star-outline": Star,
  "trash-can-outline": Trash2,
  trophy: Trophy,
  viewport: House,
  water: Waves,
  "wifi-off": WifiOff,
};

export function AppIcon({ name, ...props }) {
  const LucideIcon = APP_ICONS[name] || AlertCircle;
  return <Icon as={LucideIcon} {...props} />;
}
